
import fs from 'fs';
//  readfile
// writefile
//appendfile


// fs.readFile('./gretting.txt',(error,data)=>{
//     if(error){
//         console.log("Error reading");
//         console.log(error);
//     }
//     else{
//         console.log(data.toString());
//         console.log("Data reading");
//     }

// })

// console.log("terminating ");

//write file
// const content = "This file generated By Dynamically"
// fs.writeFile('./new_gretting.txt',content,()=>{
//     if(error) console.log("Error writing");
//     else console.log("Data Saved");

// })

//append 
// fs.appendFile('./new_gretting.txt',"new content",(error)=>{
//     if(error) console.log("Error writing");
//     else console.log("Saved");

// })

//delete file
fs.unlink("./temp.txt",(error)=> console.log(error));